2019-11-28 21:19:04,282 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-11-28 21:40:15,120 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 21:40:23,581 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 2
2019-11-28 21:47:16,575 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 21:49:01,657 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 21:49:16,612 reports.views           INFO     therapy: Rezept mit der ID: 2 aufgerufen
2019-11-28 21:49:21,393 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-11-28 21:49:26,130 reports.views           INFO     therapy: Rezept mit der ID: 3 aufgerufen
2019-11-28 21:49:31,083 reports.views           INFO     add_therapy_report: Therapiebericht gespeichert mit ID: None
2019-11-28 21:50:57,974 reports.views           INFO     therapy: Rezept mit der ID: 3 aufgerufen
2019-11-28 21:51:01,059 reports.views           INFO     add_therapy_report: Therapiebericht gespeichert mit ID: None
2019-11-28 21:53:43,038 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 21:53:51,248 reports.views           INFO     add_therapy_report: Therapiebericht gespeichert mit ID: None
2019-11-28 22:01:24,561 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 22:06:21,271 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 22:06:29,664 reports.views           INFO     add_therapy_report: Therapiebericht gespeichert mit ID: None
2019-11-28 22:09:00,869 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 22:09:07,272 reports.views           INFO     add_therapy_report: Therapiebericht gespeichert mit ID: None
2019-11-28 22:12:55,123 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 22:13:01,732 reports.views           INFO     add_therapy_report: Therapiebericht gespeichert mit ID: None
2019-11-28 22:13:19,654 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-28 22:15:45,403 reports.views           INFO     therapy: Rezept mit der ID: 3 aufgerufen
2019-11-28 22:15:50,472 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-11-29 20:00:12,785 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/urls.py changed, reloading.
2019-11-29 20:03:06,331 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-11-29 20:04:34,118 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-11-29 20:04:42,026 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 20:04:42,153 django.request          WARNING  Not Found: /favicon.ico
2019-11-29 20:05:53,879 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 20:06:58,791 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:49:20,129 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:50:49,658 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:50:49,719 django.request          ERROR    Internal Server Error: /reports/impressum/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 40, in impressum
    return render(request, 'reports/impressum.html')
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 483, in parse
    self.unclosed_block_tag(parse_until)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 544, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 8: 'block'. Looking for one of: endblock.
2019-11-29 22:51:23,824 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:55:19,425 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:55:48,675 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:56:05,844 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:56:46,501 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:57:14,799 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:57:55,697 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:58:47,506 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 22:58:49,261 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:02:20,677 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:02:22,786 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:04:57,560 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:10:29,432 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:11:31,118 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:11:33,258 reports.views           INFO     Indexseite wurde geladen
2019-11-29 23:11:47,913 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:11:50,922 reports.views           INFO     Indexseite wurde geladen
2019-11-29 23:12:02,714 reports.views           INFO     Indexseite wurde geladen
2019-11-29 23:12:06,140 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:12:09,589 reports.views           INFO     Indexseite wurde geladen
2019-11-29 23:14:52,860 reports.views           INFO     Indexseite wurde geladen
2019-11-29 23:14:55,599 reports.views           INFO     Impressumseite aufgerufen
2019-11-29 23:14:59,969 reports.views           INFO     Indexseite wurde geladen
2019-11-29 23:43:26,875 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-29 23:43:38,025 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-11-29 23:43:38,029 reports.views           INFO     search_patient: Mehrere Patienten mit dem Nachnamen Kr gefunden
2019-11-29 23:43:40,365 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-11-29 23:43:43,106 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-11-30 22:49:19,824 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-30 22:53:38,568 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-30 22:55:19,444 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-11-30 22:55:42,339 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-30 22:56:07,516 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-11-30 22:57:04,078 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-11-30 22:57:14,294 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-01 06:52:32,887 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-01 06:52:47,732 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-01 07:11:15,356 reports.views           INFO     Indexseite wurde geladen
2019-12-01 07:11:17,118 reports.views           INFO     add_patient: Formular aufgerufen
2019-12-01 07:16:41,675 reports.views           INFO     add_patient: Formular aufgerufen
2019-12-01 07:17:47,354 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-01 07:17:52,246 reports.views           INFO     add_patient: Formular aufgerufen
2019-12-01 20:38:25,662 reports.views           INFO     Indexseite wurde geladen
2019-12-01 20:38:34,298 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-01 20:38:34,300 reports.views           INFO     search_patient: Mehrere Patienten mit dem Nachnamen Kr gefunden
2019-12-01 20:38:40,455 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-01 20:38:42,996 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-01 20:38:46,027 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-01 21:01:04,401 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-01 21:01:41,748 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-01 21:01:50,748 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-02 07:41:35,426 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-02 07:45:32,572 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-02 07:46:42,188 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:13:09,407 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:14:21,277 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:14:54,284 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:15:02,228 reports.views           INFO     edit_patient: Patient mit der ID: 1 zwecks Änderung aufgerufen
2019-12-06 07:17:02,639 reports.views           INFO     edit_patient: Patient mit der ID:1 geändert
2019-12-06 07:17:02,652 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:18:45,859 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:21:34,104 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:22:29,995 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:24:05,250 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:24:28,928 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:25:00,591 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:25:13,925 reports.views           INFO     edit_patient: Patient mit der ID: 1 zwecks Änderung aufgerufen
2019-12-06 07:26:19,625 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-06 07:26:34,689 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-06 07:27:44,415 reports.views           INFO     edit_patient: Patient mit der ID: 1 zwecks Änderung aufgerufen
2019-12-06 07:28:35,132 reports.views           INFO     edit_patient: Patient mit der ID:1 geändert
2019-12-06 07:28:35,148 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:29:03,893 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:30:36,556 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:33:04,854 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:33:38,324 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:35:22,978 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:35:52,826 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:38:06,844 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:38:31,525 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:41:40,494 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:46:14,493 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:47:07,592 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:50:42,538 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:52:19,009 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:53:16,383 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:54:22,841 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:55:28,474 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:56:10,614 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:57:15,618 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 07:59:47,840 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 08:15:41,557 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 08:16:03,789 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 08:16:43,486 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 08:35:29,973 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 08:35:53,778 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 09:07:10,182 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 09:07:45,301 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 09:09:30,633 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 09:14:05,830 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 09:15:23,186 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 09:18:43,409 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 09:20:11,613 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 09:21:01,437 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:15:41,866 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 19:15:46,019 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-06 19:17:35,867 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:18:38,030 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:22:57,187 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:26:12,968 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:26:18,227 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 194, in patient
    process_single[i] = Process_report.objects.filter(therapy_id=therapy_result_item.id).count()
TypeError: 'str' object does not support item assignment
2019-12-06 19:26:39,763 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:26:42,501 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 194, in patient
    process_single[i] = str(Process_report.objects.filter(therapy_id=therapy_result_item.id).count())
TypeError: 'str' object does not support item assignment
2019-12-06 19:27:28,092 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:35:18,509 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:35:24,495 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 194, in patient
    process_single.append = Process_report.objects.filter(therapy_id=therapy_result_item.id).count()
AttributeError: 'list' object attribute 'append' is read-only
2019-12-06 19:36:00,505 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:36:06,072 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:37:20,464 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:38:30,540 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:38:34,577 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:44:32,703 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:44:32,784 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'i'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 199, in patient
    'process_single': process_single})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 115: 'i', expected 'endblock'. Did you forget to register or load this tag?
2019-12-06 19:45:13,821 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:45:13,893 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 199, in patient
    'process_single': process_single})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[i]' from 'item.process_single[i]'
2019-12-06 19:45:53,779 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:45:53,845 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 199, in patient
    'process_single': process_single})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'item.process_single[0]'
2019-12-06 19:46:13,857 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:46:13,924 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 199, in patient
    'process_single': process_single})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'process_single[0]'
2019-12-06 19:46:48,174 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:47:28,108 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:47:30,023 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:47:30,060 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 195, in patient
    assert False
AssertionError
2019-12-06 19:48:01,376 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 19:48:06,082 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:48:12,509 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 19:48:17,051 reports.views           INFO     therapy: Rezept mit der ID: 2 aufgerufen
2019-12-06 19:48:21,177 reports.views           INFO     therapy: Rezept mit der ID: 1 aufgerufen
2019-12-06 19:48:25,185 reports.views           INFO     therapy: Rezept mit der ID: 3 aufgerufen
2019-12-06 19:57:07,799 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:58:06,536 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:59:15,266 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 19:59:15,332 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 200, in patient
    'process_single': process_single})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 808, in do_for
    " %s" % token.contents)
django.template.exceptions.TemplateSyntaxError: 'for' tag received an invalid argument: for item in therapy and single in process_single
2019-12-06 20:04:39,563 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:08:17,445 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 20:08:21,337 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:08:21,372 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 196, in patient
    assert False
AssertionError
2019-12-06 20:09:03,985 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 20:09:05,675 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:09:05,718 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 196, in patient
    assert False
AssertionError
2019-12-06 20:10:04,470 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 20:10:07,300 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:10:07,336 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 196, in patient
    assert False
AssertionError
2019-12-06 20:12:44,132 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 20:12:52,088 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:12:52,125 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 198, in patient
    test = (therapy_result[0].single)
AttributeError: 'Therapy' object has no attribute 'single'
2019-12-06 20:31:29,961 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 20:31:36,407 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:31:36,447 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 199, in patient
    assert False
AssertionError
2019-12-06 20:32:38,675 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 20:32:44,476 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:33:30,551 reports.views           INFO     therapy: Rezept mit der ID: 2 aufgerufen
2019-12-06 20:33:36,061 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 2 zwecks Änderung aufgerufen
2019-12-06 20:33:43,001 reports.views           INFO     edit_therapy: Rezept mit der ID:2 geändert
2019-12-06 20:33:43,022 reports.views           INFO     therapy: Rezept mit der ID: 2 aufgerufen
2019-12-06 20:34:09,464 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 2 zwecks Änderung aufgerufen
2019-12-06 20:34:29,604 reports.views           INFO     edit_therapy: Rezept mit der ID:2 geändert
2019-12-06 20:34:29,617 reports.views           INFO     therapy: Rezept mit der ID: 2 aufgerufen
2019-12-06 20:34:48,113 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:34:53,398 reports.views           INFO     therapy: Rezept mit der ID: 1 aufgerufen
2019-12-06 20:34:55,343 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 1 zwecks Änderung aufgerufen
2019-12-06 20:35:10,843 reports.views           INFO     edit_therapy: Rezept mit der ID:1 geändert
2019-12-06 20:35:10,861 reports.views           INFO     therapy: Rezept mit der ID: 1 aufgerufen
2019-12-06 20:35:14,966 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:46:08,230 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 20:46:13,992 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 20:53:44,129 reports.views           INFO     edit_patient: Patient mit der ID: 1 zwecks Änderung aufgerufen
2019-12-06 20:53:57,229 reports.views           INFO     edit_patient: Patient mit der ID:1 geändert
2019-12-06 20:53:57,246 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 21:03:58,261 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 21:07:40,749 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-06 21:09:45,043 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 21:13:20,389 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 21:13:20,464 django.request          ERROR    Internal Server Error: /reports/therapy/4/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 250, in therapy
    'process_report': process_report_value})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/urls/resolvers.py", line 668, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_process_report' with no arguments not found. 1 pattern(s) tried: ['reports/edit/process_report/(?P<id>[^/]+)/$']
2019-12-06 21:15:10,909 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 21:15:17,472 reports.views           INFO     edit_process_report: Verlaufsprotokoll anlegen mit ID: 5
2019-12-06 21:15:24,122 reports.views           INFO     edit_process_report: Verlaufsprotokoll ändern mit ID: 5
2019-12-06 21:15:24,127 reports.views           INFO     process_report: Verlaufsprotokoll mit ID: 5 anzeigen
2019-12-06 21:15:30,437 reports.views           INFO     edit_process_report: Verlaufsprotokoll anlegen mit ID: 5
2019-12-06 21:15:36,277 reports.views           INFO     edit_process_report: Verlaufsprotokoll ändern mit ID: 5
2019-12-06 21:15:36,290 reports.views           INFO     process_report: Verlaufsprotokoll mit ID: 5 anzeigen
2019-12-06 21:15:38,659 reports.views           INFO     edit_process_report: Verlaufsprotokoll anlegen mit ID: 5
2019-12-06 21:17:03,923 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 21:18:30,977 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 21:20:04,436 reports.views           INFO     edit_process_report: Verlaufsprotokoll anlegen mit ID: 5
2019-12-06 21:20:13,132 reports.views           INFO     edit_process_report: Verlaufsprotokoll ändern mit ID: 5
2019-12-06 21:20:13,145 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 21:20:25,943 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-06 21:20:40,717 reports.views           INFO     add_process_report: Verlaufsprotokoll gespeichert mit ID: 4
2019-12-06 21:20:40,731 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 21:20:45,083 reports.views           INFO     edit_process_report: Verlaufsprotokoll anlegen mit ID: 6
2019-12-06 21:20:53,253 reports.views           INFO     edit_process_report: Verlaufsprotokoll ändern mit ID: 6
2019-12-06 21:20:53,272 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 21:35:01,503 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 21:36:52,144 reports.views           INFO     Indexseite wurde geladen
2019-12-06 21:38:46,731 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-06 21:38:50,958 reports.views           INFO     Indexseite wurde geladen
2019-12-06 21:40:41,553 reports.views           INFO     search_patient: Suchkriterien: Nachname:  ; Geburtsdatum: 
2019-12-06 21:40:41,554 reports.views           INFO     search_patient: Mehrere Patienten mit dem Vornamen: Jana gefunden
2019-12-06 21:40:44,805 reports.views           INFO     patient: Patient mit der ID: 4 aufgerufen
2019-12-06 22:06:12,018 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-06 22:06:31,639 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-06 22:07:15,410 reports.views           INFO     add_therapy: Rezept für Patient mit ID: 4 angelegt
2019-12-06 22:07:15,420 reports.views           INFO     patient: Patient mit der ID: 4 aufgerufen
2019-12-06 22:07:46,435 reports.views           INFO     Indexseite wurde geladen
2019-12-06 22:07:48,603 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-06 22:07:48,604 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-06 22:07:50,017 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 22:07:56,356 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 22:08:01,304 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-06 22:08:16,983 reports.views           INFO     edit_therapy: Rezept mit der ID:4 geändert
2019-12-06 22:08:16,991 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-06 22:16:34,962 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 22:16:37,451 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 22:16:41,102 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-06 22:17:17,326 django.request          ERROR    Internal Server Error: /reports/add/therapy/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 227, in add_therapy
    assert False
AssertionError
2019-12-06 22:33:46,961 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-06 22:33:58,563 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-06 22:34:09,249 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-06 22:34:20,927 reports.views           INFO     add_therapy: Rezept für Patient mit ID: 1 angelegt
2019-12-06 22:34:20,949 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-06 22:34:27,005 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-06 22:34:40,676 reports.views           INFO     add_therapy_report: Therapiebericht gespeichert mit ID: None
2019-12-07 06:46:51,670 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-07 09:47:06,092 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-07 12:48:23,496 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-07 12:50:07,705 reports.views           INFO     Indexseite wurde geladen
2019-12-07 12:50:19,462 reports.views           INFO     Indexseite wurde geladen
2019-12-07 12:50:36,949 reports.views           INFO     Indexseite wurde geladen
2019-12-07 12:50:46,933 reports.views           INFO     add_patient: Formular aufgerufen
2019-12-07 12:52:48,399 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-07 12:54:23,080 reports.views           INFO     add_patient: Formular aufgerufen
2019-12-07 12:55:37,852 reports.views           INFO     Indexseite wurde geladen
2019-12-07 12:56:25,965 reports.views           INFO     search_patient: Suchkriterien: Nachname: Krings ; Geburtsdatum: 
2019-12-07 12:56:25,967 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Krings gefunden
2019-12-07 12:56:27,690 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-07 12:56:32,273 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-07 12:56:54,877 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 12:56:58,393 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-07 12:57:02,271 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-07 12:57:04,895 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 12:57:16,929 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-07 12:57:24,148 reports.views           INFO     edit_therapy: Rezept mit der ID:4 geändert
2019-12-07 12:57:24,162 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 12:58:36,549 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-07 13:00:30,024 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-07 13:04:37,254 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-07 13:06:37,187 django.request          ERROR    Internal Server Error: /reports/edit/therapy/4/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: reports_therapy.therapy_frequence

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 241, in edit_therapy
    item = get_object_or_404(Therapy, id=id)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 93, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: reports_therapy.therapy_frequence
2019-12-07 13:06:46,429 reports.views           INFO     Indexseite wurde geladen
2019-12-07 13:06:49,001 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-07 13:06:49,003 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-07 13:06:50,606 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: reports_therapy.therapy_frequence

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 204, in patient
    for therapy_result_item in therapy_result:
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: reports_therapy.therapy_frequence
2019-12-07 13:07:29,816 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-07 13:07:38,248 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:10:49,539 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:10:59,584 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-07 13:11:10,462 reports.views           INFO     edit_therapy: Rezept mit der ID:4 geändert
2019-12-07 13:11:10,471 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:13:06,374 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:16:06,998 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:16:36,101 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:16:47,681 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-07 13:17:17,649 reports.views           INFO     edit_therapy: Rezept mit der ID:4 geändert
2019-12-07 13:17:17,661 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:17:35,514 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:19:29,956 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-07 13:19:56,881 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-07 13:21:57,584 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:22:07,433 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:22:28,976 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:22:33,975 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:23:34,037 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:23:39,396 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:24:09,242 reports.views           INFO     Indexseite wurde geladen
2019-12-07 13:24:11,914 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-07 13:24:14,736 reports.views           INFO     search_doctor: Arzt gefunden mit dem Suchbegriff: Sch
2019-12-07 13:24:14,742 reports.views           INFO     doctor: Arzt mit der ID: 4 aufgerufen
2019-12-07 13:24:23,376 reports.views           INFO     Indexseite wurde geladen
2019-12-07 13:24:24,525 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-07 13:24:26,912 reports.views           INFO     search_doctor: mehr als einen Arzt gefunden mit dem Suchbegriff: M
2019-12-07 13:24:28,723 reports.views           INFO     doctor: Arzt mit der ID: 1 aufgerufen
2019-12-07 13:24:31,126 reports.views           INFO     edit_doctor: Bearbeitungsformular aufgerufen ID: 1
2019-12-07 13:25:19,500 reports.views           INFO     edit_doctor: Bearbeitungsformular aufgerufen ID: 1
2019-12-07 13:25:28,224 reports.views           INFO     edit_doctor: Daten werden gespeichert
2019-12-07 13:25:28,236 reports.views           INFO     doctor: Arzt mit der ID: 1 aufgerufen
2019-12-07 13:25:40,191 reports.views           INFO     Indexseite wurde geladen
2019-12-07 13:25:42,942 reports.views           INFO     search_patient: Suchkriterien: Nachname: KR ; Geburtsdatum: 
2019-12-07 13:25:42,944 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: KR gefunden
2019-12-07 13:25:44,675 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-07 13:25:47,603 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-07 13:25:57,590 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:26:54,050 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:26:58,012 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:27:46,126 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:27:53,644 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:31:06,556 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:31:13,362 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:33:27,058 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:33:32,077 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:34:38,804 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:36:00,121 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:36:06,837 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:36:58,047 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:37:02,921 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:38:22,547 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-07 13:38:26,751 reports.views           INFO     show_therapy_report: Therapiebericht mit ID: 4 gedruckt
2019-12-07 13:40:37,317 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-08 10:21:06,077 reports.views           INFO     Indexseite wurde geladen
2019-12-08 10:29:35,602 django.request          WARNING  Not Found: /favicon.ico
2019-12-08 10:49:25,703 reports.views           INFO     Indexseite wurde geladen
2019-12-08 10:50:44,957 reports.views           INFO     Indexseite wurde geladen
2019-12-08 12:41:40,029 reports.views           INFO     Indexseite wurde geladen
2019-12-08 12:41:58,840 reports.views           INFO     Indexseite wurde geladen
2019-12-08 12:42:02,247 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-08 12:42:02,249 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-08 12:42:04,045 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 12:42:07,993 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 12:42:12,231 reports.views           INFO     edit_therapy_report: Therapybericht anlegen mit ID: 3
2019-12-08 13:00:08,892 reports.views           INFO     Indexseite wurde geladen
2019-12-08 13:00:17,045 reports.views           INFO     Indexseite wurde geladen
2019-12-08 13:00:20,205 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-08 13:00:20,214 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-08 13:00:22,412 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 13:00:25,793 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 13:00:30,046 reports.views           INFO     edit_therapy_report: Therapybericht anlegen mit ID: 3
2019-12-08 13:04:58,112 reports.views           INFO     Indexseite wurde geladen
2019-12-08 13:05:00,858 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-08 13:05:00,860 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-08 13:05:02,829 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 13:05:05,965 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 13:05:07,904 reports.views           INFO     edit_therapy_report: Therapybericht anlegen mit ID: 3
2019-12-08 13:20:39,668 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-08 13:21:20,694 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-08 13:27:39,882 reports.views           INFO     Indexseite wurde geladen
2019-12-08 13:27:44,742 reports.views           INFO     search_patient: Suchkriterien: Nachname: KR ; Geburtsdatum: 
2019-12-08 13:27:44,744 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: KR gefunden
2019-12-08 13:27:50,920 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 13:27:53,453 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-08 13:29:40,233 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-08 13:29:51,665 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-08 13:29:54,056 reports.views           INFO     Indexseite wurde geladen
2019-12-08 13:29:56,760 reports.views           INFO     search_patient: Suchkriterien: Nachname: KR ; Geburtsdatum: 
2019-12-08 13:29:56,761 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: KR gefunden
2019-12-08 13:29:58,355 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 13:29:59,938 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-08 13:30:38,007 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 13:30:41,280 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 13:30:45,099 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-08 13:30:52,214 reports.views           INFO     edit_therapy: Rezept mit der ID:4 geändert
2019-12-08 13:30:52,225 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 13:31:50,778 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 13:35:44,430 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 13:35:44,511 django.request          ERROR    Internal Server Error: /reports/therapy/4/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 263, in therapy
    'process_report': process_report_value})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 959, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
2019-12-08 13:37:20,768 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 20:35:15,926 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-08 20:39:35,565 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-08 20:43:15,020 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-08 20:43:41,348 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-08 20:43:59,256 reports.views           INFO     edit_therapy: Rezept mit der ID:4 geändert
2019-12-08 20:43:59,267 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 20:44:10,592 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 20:44:27,807 reports.views           INFO     add_therapy: Formular aufgerufen um eine Rezept anzulegen
2019-12-08 20:48:09,264 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 20:49:51,699 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 20:50:34,693 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 20:57:46,193 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 20:58:59,573 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:00:39,747 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:03:17,603 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:03:47,597 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:05:51,217 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:06:10,103 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:06:33,661 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:08:35,819 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:14:38,807 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:23:55,746 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:30:55,885 reports.views           INFO     Indexseite wurde geladen
2019-12-08 21:34:03,537 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-08 21:34:03,539 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-08 21:34:06,687 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:34:13,191 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 21:34:15,815 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-08 21:34:22,700 reports.views           INFO     edit_therapy: Rezept mit der ID:4 geändert
2019-12-08 21:34:22,717 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-08 21:34:27,728 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-08 21:36:52,603 django.request          WARNING  Not Found: /favicon.ico
2019-12-08 21:37:56,250 reports.views           INFO     Indexseite wurde geladen
2019-12-08 21:38:14,372 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-08 21:38:14,374 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-08 21:38:16,121 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-08 21:38:47,149 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-08 21:38:53,324 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-08 21:39:05,854 reports.views           INFO     edit_therapy: Rezept mit der ID:7 geändert
2019-12-08 21:39:05,866 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-08 22:20:19,005 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-08 22:20:32,536 reports.views           INFO     add_therapy_report: Therapiebericht gespeichert mit ID: None
2019-12-09 17:50:33,717 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-09 17:51:42,005 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-09 17:52:39,526 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-09 17:53:14,563 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 17:53:21,006 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 17:55:31,725 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 17:55:52,326 reports.views           INFO     edit_therapy: Rezept mit der ID:7 geändert
2019-12-09 17:55:52,383 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 17:56:03,043 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 18:01:15,193 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:01:26,685 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-09 18:01:39,770 reports.views           INFO     Indexseite wurde geladen
2019-12-09 18:01:42,043 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-09 18:01:42,045 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-09 18:01:44,199 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 18:01:57,522 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-09 18:02:03,411 django.request          ERROR    Internal Server Error: /reports/show_therapy_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 455, in show_therapy_report
    assert False
AssertionError
2019-12-09 18:02:03,554 django.request          WARNING  Not Found: /favicon.ico
2019-12-09 18:03:09,051 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:23:15,309 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:23:21,559 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:23:33,932 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 18:23:35,876 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 18:23:59,066 reports.views           INFO     edit_therapy: Rezept mit der ID:7 geändert
2019-12-09 18:23:59,079 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 18:24:04,642 django.request          WARNING  Not Found: /reports/show_therapy_report/
2019-12-09 18:25:03,520 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:25:10,543 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 18:25:10,638 django.request          ERROR    Internal Server Error: /reports/show_therapy_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 456, in show_therapy_report
    assert False
AssertionError
2019-12-09 18:29:33,024 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:29:41,368 reports.views           INFO     edit_therapy: Test
2019-12-09 18:30:09,757 reports.views           INFO     edit_therapy: Test
2019-12-09 18:30:21,376 reports.views           INFO     edit_therapy: Test
2019-12-09 18:32:25,175 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:32:29,098 reports.views           INFO     Indexseite wurde geladen
2019-12-09 18:32:30,854 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-09 18:32:30,856 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-09 18:32:32,707 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 18:32:46,369 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-09 18:32:49,332 django.request          ERROR    Internal Server Error: /reports/show_therapy_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 461, in show_therapy_report
    assert False
AssertionError
2019-12-09 18:32:57,616 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 18:33:00,721 django.request          ERROR    Internal Server Error: /reports/show_therapy_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 461, in show_therapy_report
    assert False
AssertionError
2019-12-09 18:33:37,767 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:33:42,648 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 18:33:44,703 django.request          ERROR    Internal Server Error: /reports/show_therapy_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 461, in show_therapy_report
    assert False
AssertionError
2019-12-09 18:34:10,206 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:34:20,312 reports.views           INFO     edit_therapy: Test
2019-12-09 18:34:31,398 reports.views           INFO     edit_therapy: Test
2019-12-09 18:36:54,170 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:37:00,420 reports.views           INFO     test für Kein Endedatum
2019-12-09 18:37:00,427 reports.views           INFO     edit_therapy: Test
2019-12-09 18:37:04,412 reports.views           INFO     test für Kein Endedatum
2019-12-09 18:37:04,415 reports.views           INFO     edit_therapy: Test
2019-12-09 18:37:19,759 reports.views           INFO     test für Kein Endedatum
2019-12-09 18:37:19,763 reports.views           INFO     edit_therapy: Test
2019-12-09 18:52:33,590 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 18:52:53,425 reports.views           INFO     Indexseite wurde geladen
2019-12-09 18:52:58,819 reports.views           INFO     search_patient: Suchkriterien: Nachname: KR ; Geburtsdatum: 
2019-12-09 18:52:58,821 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: KR gefunden
2019-12-09 18:53:00,970 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 18:53:07,156 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 18:53:17,638 reports.views           INFO     test für Kein Endedatum
2019-12-09 18:53:17,642 reports.views           INFO     edit_therapy: Test
2019-12-09 18:53:30,497 reports.views           INFO     test für Kein Endedatum
2019-12-09 18:53:30,509 reports.views           INFO     edit_therapy: Rezept mit der ID:7 geändert
2019-12-09 18:53:30,509 reports.views           INFO     edit_therapy: Test
2019-12-09 18:53:34,855 reports.views           INFO     test für Kein Endedatum
2019-12-09 18:53:34,896 django.request          ERROR    Internal Server Error: /reports/show_therapy_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 465, in show_therapy_report
    assert False
AssertionError
2019-12-09 19:07:33,039 reports.views           INFO     test für Kein Endedatum
2019-12-09 19:07:33,078 django.request          ERROR    Internal Server Error: /reports/show_therapy_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 465, in show_therapy_report
    assert False
AssertionError
2019-12-09 19:07:44,655 reports.views           INFO     test für Kein Endedatum
2019-12-09 19:07:44,690 django.request          ERROR    Internal Server Error: /reports/show_therapy_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 465, in show_therapy_report
    assert False
AssertionError
2019-12-09 19:07:51,860 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:07:57,383 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 19:08:29,786 django.request          WARNING  Not Found: /reports/edit/therapy/7/edit_therapy
2019-12-09 19:09:46,655 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:09:50,773 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 19:10:12,793 django.request          WARNING  Not Found: /reports/edit/therapy/7/edit/therapy
2019-12-09 19:11:43,871 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 19:11:47,773 django.request          WARNING  Not Found: /reports/edit/therapy
2019-12-09 19:12:49,410 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 19:12:53,624 django.request          WARNING  Not Found: /reports/edit/therapy/
2019-12-09 19:13:16,431 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 19:13:19,793 django.request          WARNING  Not Found: /reports/edit/therapy//123
2019-12-09 19:15:05,079 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 19:15:10,202 reports.views           INFO     edit_therapy: Rezept mit der ID:7 geändert
2019-12-09 19:15:10,215 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:24:03,892 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 19:24:40,514 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:24:40,622 django.request          ERROR    Internal Server Error: /reports/therapy/7/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'elsif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 263, in therapy
    'process_report': process_report_value})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 42: 'elsif', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2019-12-09 19:25:13,110 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:25:13,189 django.request          ERROR    Internal Server Error: /reports/therapy/7/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 263, in therapy
    'process_report': process_report_value})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 959, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
2019-12-09 19:26:24,135 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:26:24,208 django.request          ERROR    Internal Server Error: /reports/therapy/7/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 263, in therapy
    'process_report': process_report_value})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 959, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
2019-12-09 19:27:48,456 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:27:48,540 django.request          ERROR    Internal Server Error: /reports/therapy/7/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 263, in therapy
    'process_report': process_report_value})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 959, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
2019-12-09 19:28:16,696 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:28:16,770 django.request          ERROR    Internal Server Error: /reports/therapy/7/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 263, in therapy
    'process_report': process_report_value})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 959, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
2019-12-09 19:36:39,359 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:36:39,452 django.request          ERROR    Internal Server Error: /reports/therapy/7/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 263, in therapy
    'process_report': process_report_value})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/defaulttags.py", line 959, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
2019-12-09 19:38:57,574 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:39:09,340 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 19:39:15,897 reports.views           INFO     edit_therapy: Rezept mit der ID:7 geändert
2019-12-09 19:39:15,908 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:41:19,393 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:42:38,579 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:43:39,659 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:43:48,296 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 7 zwecks Änderung aufgerufen
2019-12-09 19:51:34,203 reports.views           INFO     edit_therapy: Rezept mit der ID:7 geändert
2019-12-09 19:51:34,232 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 19:55:35,914 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 19:56:16,412 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 20:12:30,442 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:18:23,919 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:22:54,630 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:24:20,440 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:25:25,993 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:26:23,771 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:27:55,991 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:30:13,151 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:30:49,664 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:32:07,094 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:32:59,960 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:33:17,742 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:33:48,816 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:34:18,208 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:34:40,489 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:34:41,889 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:35:14,478 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:35:32,381 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:42:10,239 reports.views           INFO     Indexseite wurde geladen
2019-12-09 20:42:12,868 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 20:43:23,914 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-09 20:43:31,469 reports.views           INFO     Indexseite wurde geladen
2019-12-09 20:43:33,563 reports.views           INFO     search_patient: Suchkriterien: Nachname: kr ; Geburtsdatum: 
2019-12-09 20:43:33,565 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: kr gefunden
2019-12-09 20:43:35,679 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-09 20:43:40,575 reports.views           INFO     therapy: Rezept mit der ID: 7 aufgerufen
2019-12-09 20:54:26,629 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 20:56:56,102 reports.views           INFO     Indexseite wurde geladen
2019-12-09 20:56:58,712 reports.views           INFO     search_patient: Suchkriterien: Nachname: M ; Geburtsdatum: 
2019-12-09 20:56:58,714 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: M gefunden
2019-12-09 20:57:01,214 reports.views           INFO     Indexseite wurde geladen
2019-12-09 20:57:04,990 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 20:57:07,452 django.request          ERROR    Internal Server Error: /reports/search/doctor/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 129, in search_doctor
    if len(doctors_list == 0):
TypeError: object of type 'bool' has no len()
2019-12-09 20:57:51,448 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 20:58:02,316 reports.views           INFO     search_doctor: mehr als einen Arzt gefunden mit dem Suchbegriff: M
2019-12-09 20:58:22,450 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 20:58:27,587 reports.views           INFO     search_doctor: Arzt gefunden mit dem Suchbegriff: Weiden
2019-12-09 20:58:27,593 reports.views           INFO     doctor: Arzt mit der ID: 1 aufgerufen
2019-12-09 20:58:51,337 django.request          WARNING  Not Found: /favicon.ico
2019-12-09 21:00:10,348 reports.views           INFO     doctor: Arzt mit der ID: 1 aufgerufen
2019-12-09 21:02:15,482 reports.views           INFO     doctor: Arzt mit der ID: 1 aufgerufen
2019-12-09 21:02:33,688 reports.views           INFO     doctor: Arzt mit der ID: 1 aufgerufen
2019-12-09 21:10:27,958 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 21:12:57,858 reports.views           INFO     doctor: Arzt mit der ID: 1 aufgerufen
2019-12-09 21:13:02,084 reports.views           INFO     Indexseite wurde geladen
2019-12-09 21:13:04,855 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 21:13:07,172 django.request          ERROR    Internal Server Error: /reports/search/doctor/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 131, in search_doctor
    assert False
AssertionError
2019-12-09 21:16:13,821 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 21:16:17,929 django.request          ERROR    Internal Server Error: /reports/search/doctor/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 131, in search_doctor
    assert False
AssertionError
2019-12-09 21:17:05,319 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 21:17:14,398 django.request          ERROR    Internal Server Error: /reports/search/doctor/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 131, in search_doctor
    assert False
AssertionError
2019-12-09 21:20:04,908 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 21:48:06,661 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 21:48:32,844 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 21:50:00,940 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 21:50:07,241 django.request          ERROR    Internal Server Error: /reports/search/doctor/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 134, in search_doctor
    assert False
AssertionError
2019-12-09 21:50:51,688 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 21:50:55,967 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 21:50:57,929 reports.views           INFO     search_doctor: Arzt gefunden mit dem Suchbegriff: Schmitz
2019-12-09 21:50:57,935 reports.views           INFO     doctor: Arzt mit der ID: 4 aufgerufen
2019-12-09 21:51:05,655 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 21:51:24,959 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 21:51:28,583 reports.views           INFO     search_doctor: mehr als einen Arzt gefunden mit dem Suchbegriff: Schmitz
2019-12-09 21:53:07,149 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-09 21:53:13,854 reports.views           INFO     search_doctor: Arzt gefunden mit dem Suchbegriff: Schmitz
2019-12-09 21:53:13,886 reports.views           INFO     doctor: Arzt mit der ID: 4 aufgerufen
2019-12-09 21:53:21,360 reports.views           INFO     Indexseite wurde geladen
2019-12-09 21:53:22,402 reports.views           INFO     search_doctor: Keinen Suchbegriff eingegeben
2019-12-09 21:53:26,101 reports.views           INFO     search_doctor: Arzt gefunden mit dem Suchbegriff: Weiden
2019-12-09 21:53:26,106 reports.views           INFO     doctor: Arzt mit der ID: 1 aufgerufen
2019-12-11 20:18:28,457 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/models.py changed, reloading.
2019-12-11 20:46:00,450 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-11 20:46:26,995 reports.views           INFO     Indexseite wurde geladen
2019-12-11 20:46:29,409 reports.views           INFO     search_patient: Suchkriterien: Nachname: Kr ; Geburtsdatum: 
2019-12-11 20:46:29,411 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: Kr gefunden
2019-12-11 20:46:32,355 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-11 20:47:30,220 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-11 20:47:37,088 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 20:48:34,546 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 20:50:58,937 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 20:52:59,552 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 20:53:32,193 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 20:55:18,722 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 20:57:37,599 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:01:02,839 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:02:31,492 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:02:38,819 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:04:09,018 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:09:57,678 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-11 21:10:04,518 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:13:26,601 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-11 21:14:01,814 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:17:50,406 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:17:50,480 django.request          ERROR    Internal Server Error: /reports/add/process_report/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 291, in add_process_report
    return render(request, 'reports/process_report_form.html', {'form': form})
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '"' from 'form.process_content_3"'
2019-12-11 21:18:28,913 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:19:45,332 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:24:47,085 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-11 21:24:50,012 reports.views           INFO     add_process_report: Verlaufsprotokoll anlegen mit ID: 4
2019-12-11 21:26:24,684 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/forms.py changed, reloading.
2019-12-11 21:41:04,845 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-11 21:48:38,692 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-11 21:49:04,153 reports.views           INFO     edit_process_report: Verlaufsprotokoll anlegen mit ID: 5
2019-12-11 21:49:29,323 reports.views           INFO     edit_process_report: Verlaufsprotokoll ändern mit ID: 5
2019-12-11 21:49:29,331 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 19:28:19,506 django.utils.autoreload INFO     /Users/nkrings/PycharmProjects/Logopaedie/reports/views.py changed, reloading.
2019-12-12 19:28:31,351 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-12 19:28:37,536 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 19:32:43,693 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 19:39:34,494 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 19:40:52,229 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 19:44:45,782 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 19:53:01,743 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 19:57:03,115 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:02:58,958 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:05:56,850 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:07:02,417 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:08:11,133 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:08:31,697 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:10:09,710 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:10:45,724 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:24:24,119 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:25:29,650 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:25:55,350 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:27:41,354 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:28:32,240 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:29:46,651 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:30:16,144 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:31:56,667 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:32:29,549 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:33:04,321 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:33:24,851 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:35:09,445 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:36:04,086 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:36:48,035 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:38:46,770 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:39:08,717 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:42:12,539 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:46:20,897 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:49:14,799 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:50:09,626 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:51:21,952 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:52:02,864 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:52:41,409 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:56:05,854 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 20:56:40,562 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:00:35,446 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:04:32,644 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:10:03,989 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:12:04,492 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:13:42,688 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:24:51,336 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:26:02,662 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:27:15,756 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:28:11,740 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:29:20,918 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:32:55,120 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:36:55,831 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:39:37,582 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:41:39,076 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:42:04,235 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 21:42:16,424 reports.views           INFO     edit_process_report: Verlaufsprotokoll anlegen mit ID: 6
2019-12-12 21:42:51,971 reports.views           INFO     edit_process_report: Verlaufsprotokoll ändern mit ID: 6
2019-12-12 21:42:51,981 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 22:04:51,681 reports.views           INFO     Indexseite wurde geladen
2019-12-12 22:05:09,439 reports.views           INFO     Indexseite wurde geladen
2019-12-12 22:05:12,413 reports.views           INFO     search_patient: Suchkriterien: Nachname: kr ; Geburtsdatum: 
2019-12-12 22:05:12,414 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: kr gefunden
2019-12-12 22:05:14,785 django.request          ERROR    Internal Server Error: /reports/patient/1/
Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: reports_therapy.therapy_rid_of

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nkrings/PycharmProjects/Logopaedie/reports/views.py", line 210, in patient
    for therapy_result_item in therapy_result:
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/nkrings/.virtualenvs/Logopaedie/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: reports_therapy.therapy_rid_of
2019-12-12 22:16:04,775 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-12 22:24:36,984 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-12 22:30:27,964 reports.views           INFO     Indexseite wurde geladen
2019-12-12 22:35:58,501 reports.views           INFO     Indexseite wurde geladen
2019-12-12 22:36:05,419 reports.views           INFO     Indexseite wurde geladen
2019-12-12 22:36:08,004 reports.views           INFO     search_patient: Suchkriterien: Nachname: kr ; Geburtsdatum: 
2019-12-12 22:36:08,006 reports.views           INFO     search_patient: Mehrere Patienten mit dem Namen: kr gefunden
2019-12-12 22:36:10,768 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
2019-12-12 22:36:13,127 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 22:36:45,767 reports.views           INFO     therapy: Rezept mit der ID: 4 aufgerufen
2019-12-12 22:37:49,476 reports.views           INFO     Indexseite wurde geladen
2019-12-12 22:37:50,128 django.request          WARNING  Not Found: /favicon.ico
2019-12-13 12:42:05,749 reports.views           INFO     edit_therapy: Rezeptformular des Patienten mit der ID: 4 zwecks Änderung aufgerufen
2019-12-13 12:45:46,802 reports.views           INFO     patient: Patient mit der ID: 1 aufgerufen
